---
title: "Graphics Contest"
subtitle: "Due: October 31, 2023"
format:
  html:
    theme:
      light: 
        - cosmo
        - psets.scss
      dark: darkly
    fontsize: 1.2em
    highlight-style: atom-one
    toc: true
    toc-depth: 2
    html-math-method: katex
    embed-resources: true
    title-block-banner: linear-gradient(120deg, rgba(156, 79, 150, 1) 0%, rgba(255, 99, 85, 1) 20%, rgba(251,169,73,1) 40%, rgba(250, 228, 66, 1) 60%, rgba(139,212,72,1) 80%, rgba(42, 168, 242, 1) 100%)
    title-block-banner-color: white
    smooth-scroll: true
---

While we use the PGL graphics library fairly extensively for projects throughout this course, there are still many more things that could possibly be done! To give you a chance to spread your creative wings and explore the capabilities of the library in greater depth, I am pleased to announce the CS 151 Graphics Contest.

Each of you is eligible to submit one entry for the contest, where an entry consists of a program that uses the Portable Graphics Library (PGL). You are free to use any of the capabilities in that library, including those described in the online documentation. To get started, you can grab the starting repository below.

```{=html}
<a href='https://classroom.github.com/a/uJdT7Je9' target="_blank" class="btn btn-info" style='margin:auto; display: block; width:50%;'>Give me the materials!</a>
```
<br>

# Selection Criteria
Assuming 10 or more total submissions, a prize will be awarded in each of two categories:

- _Aesthetic merit_ -- This prize is awarded based on the aesthetic value of the entry.
- _Algorithmic sophistication_ -- This prize will be based on the difficulty of the underlying programming and the sophistication of the displayed images.

If fewer than 10 entries are received, then only a single joint prize will be awarded. In both categories, programming style will be part of the evaluation. You do not need to specify a category; all entries will be eligible for either prize.

# Prizes
The grand prize in each of the categories will be that I will replace whatever individual score most negatively affects your grade--which may be a problem set, project, or exam--with a 100% in the computation of the final grade. Those who submit serious entries will also get a ticket for a drawing for a 10% single assignment/exam boost at the end of the semester.

# Official Rules

#. Only students registered in CS 151 are eligible to submit entries in the contest.
#. Only one entry per person will be accepted.
#. All entries must be submitted by 11:59pm on Tuesday, October 31.
#. You are required to do all your graphical operations using the classes from the Portable Graphics Library. In particular, you may not dig into the source code for `pgl.py` or use other features of the TKinter library on which PGL is based.
#. Your entry may not set a window size larger than 1600x1200 pixels.
#. Contest entries should be sensitive to Willamette's individual and cultural diversity. Programs that have the effects of perpetuating negative stereotypes will not be considered for prizes.
